# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'WineUp' do
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'

  target 'WineUpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WineUpUITests' do
    # Pods for testing
  end

end
